coverage:
  if: true
  paths:
    - coverage.out

codeToTestRatio:
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'

testExecutionTime:
  if: true

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}

comment:
  if: github.event_name == 'push' && github.ref_name == 'main'
  github:
    token: ${{ secrets.GITHUB_TOKEN }}
    type: pr
  hideFooterLink: true
  deletePrevious: true

summary:
  if: true
  hideFooterLink: true

report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
  path: report.json
