coverage:
  if: true
  paths:
    - build/report/coverage.out
codeToTestRatio:
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  if: true
comment:
  if: is_pull_request
  hideFooterLink: false
summary:
  if: is_pull_request
  hideFooterLink: false
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
report:
  if: true
  datastores:
    - artifact://${GITHUB_REPOSITORY}