name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract Go version from go.mod
        id: go-version
        run: |
          go_version=$(grep '^go ' go.mod | cut -d ' ' -f 2)
          echo "go-version=$go_version" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: make test
