name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get go version
        id: go-version
        run: |
          go_version=$(grep '^go ' go.mod | cut -d ' ' -f 2)
          echo "go-version=$go_version" >> $GITHUB_ENV

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}

      - run: go mod tidy

      - run: make test

      - name: Install octocov
        run: go install github.com/k1LoW/octocov@latest

      - name: Generate coverage report with octocov
        run: |
          go test -coverprofile=coverage.out ./...
          octocov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: report.json
